import {typedValues} from "../utils/utils";

// a list of all keyboard shortcuts.
export const GlobalActions = {
   OpenFile: "OpenFile",
   ImportTicCart: "ImportTicCart",
   SaveFile: "SaveFile",
   NewFile: "NewFile",

   Panic: "Panic",
   Undo: "Undo",
   Redo: "Redo",
   ExportReleaseBuild: "ExportReleaseBuild",
   ExportDebugBuild: "ExportDebugBuild",
   ToggleDebugMode: "ToggleDebugMode",
   TogglePreferencesPanel: "TogglePreferencesPanel",
   ToggleDebugPanel: "ToggleDebugPanel",
   FocusPattern: "FocusPattern",
   ToggleWaveformEditor: "ToggleWaveformEditor",
   ToggleInstrumentPanel: "ToggleInstrumentPanel",
   CycleTic80PanelSize: "CycleTic80PanelSize",
   ToggleOnScreenKeyboard: "ToggleOnScreenKeyboard",
   ToggleAdvancedEditPanel: "ToggleAdvancedEditPanel",
   TogglePatternEditor: "TogglePatternEditor",
   ToggleCartStatsPanel: "ToggleCartStatsPanel",
   ToggleSongSettingsPanel: "ToggleSongSettingsPanel",
   ToggleEncodingUtilsPanel: "ToggleEncodingUtilsPanel",
   PlayFromPosition: "PlayFromPosition",
   PlayPattern: "PlayPattern",
   PlaySong: "PlaySong",
   PlayRow: "PlayRow",
   //PlayStop: "PlayStop",
   ToggleEditMode: "ToggleEditMode",
   DecreaseOctave: "DecreaseOctave",
   IncreaseOctave: "IncreaseOctave",
   DecreaseInstrument: "DecreaseInstrument",
   IncreaseInstrument: "IncreaseInstrument",

   IncreaseEditStep: "IncreaseEditStep",
   DecreaseEditStep: "DecreaseEditStep",
   IncreaseTempo: "IncreaseTempo",
   DecreaseTempo: "DecreaseTempo",
   IncreaseSpeed: "IncreaseSpeed",
   DecreaseSpeed: "DecreaseSpeed",
   NextSongOrder: "NextSongOrder",
   PreviousSongOrder: "PreviousSongOrder",
   ToggleKeyboardNoteInput: "ToggleKeyboardNoteInput",
   ToggleMidiNoteInput: "ToggleMidiNoteInput",
   ToggleMuteChannel1: "ToggleMuteChannel1",
   ToggleMuteChannel2: "ToggleMuteChannel2",
   ToggleMuteChannel3: "ToggleMuteChannel3",
   ToggleMuteChannel4: "ToggleMuteChannel4",
   ToggleSoloChannel1: "ToggleSoloChannel1",
   ToggleSoloChannel2: "ToggleSoloChannel2",
   ToggleSoloChannel3: "ToggleSoloChannel3",
   ToggleSoloChannel4: "ToggleSoloChannel4",
   UnmuteUnsoloAllChannels: "UnmuteUnsoloAllChannels",

   SetLoopOff: "SetLoopOff",
   SetLoopSong: "SetLoopSong",
   SetLoopSelectionInSongOrder: "SetLoopSelectionInSongOrder",
   SetLoopPattern: "SetLoopPattern",
   SetLoopHalfPattern: "SetLoopHalfPattern",
   SetLoopQuarterPattern: "SetLoopQuarterPattern",
   SetLoopSelectionInPattern: "SetLoopSelectionInPattern",
   ToggleLoopModeOff: "ToggleLoopModeOff",
   NextLoopMode: "NextLoopMode",
   PreviousLoopMode: "PreviousLoopMode",

   TransposeSelectionUpSemitone: "TransposeSelectionUpSemitone",
   TransposeSelectionDownSemitone: "TransposeSelectionDownSemitone",
   TransposeSelectionUpOctave: "TransposeSelectionUpOctave",
   TransposeSelectionDownOctave: "TransposeSelectionDownOctave",
   IncrementInstrumentInSelection: "IncrementInstrumentInSelection",
   DecrementInstrumentInSelection: "DecrementInstrumentInSelection",

   Copy: "Copy",
   Paste: "Paste",
   Cut: "Cut",

   InsertNoteCut: "InsertNoteCut",
   ClearCell: "ClearCell",
   ClearField: "ClearField",
   SelectAll: "SelectAll",

   // Keyboard note input (typing piano) via global shortcuts.
   // These correspond to the legacy mapping in src/midi/keyboard_input.ts.
   KeyboardNote01_C: "KeyboardNote01_C",
   KeyboardNote02_Csharp: "KeyboardNote02_Csharp",
   KeyboardNote03_D: "KeyboardNote03_D",
   KeyboardNote04_Dsharp: "KeyboardNote04_Dsharp",
   KeyboardNote05_E: "KeyboardNote05_E",
   KeyboardNote06_F: "KeyboardNote06_F",
   KeyboardNote07_Fsharp: "KeyboardNote07_Fsharp",
   KeyboardNote08_G: "KeyboardNote08_G",
   KeyboardNote09_Gsharp: "KeyboardNote09_Gsharp",
   KeyboardNote10_A: "KeyboardNote10_A",
   KeyboardNote11_Asharp: "KeyboardNote11_Asharp",
   KeyboardNote12_B: "KeyboardNote12_B",
   KeyboardNote13_C: "KeyboardNote13_C",
   KeyboardNote14_Csharp: "KeyboardNote14_Csharp",
   KeyboardNote15_D: "KeyboardNote15_D",
   KeyboardNote16_Dsharp: "KeyboardNote16_Dsharp",
   KeyboardNote17_E: "KeyboardNote17_E",
   KeyboardNote18_F: "KeyboardNote18_F",
   KeyboardNote19_Fsharp: "KeyboardNote19_Fsharp",
   KeyboardNote20_G: "KeyboardNote20_G",
   KeyboardNote21_Gsharp: "KeyboardNote21_Gsharp",
   KeyboardNote22_A: "KeyboardNote22_A",
   KeyboardNote23_Asharp: "KeyboardNote23_Asharp",
   KeyboardNote24_B: "KeyboardNote24_B",
   KeyboardNote25_C: "KeyboardNote25_C",
} as const;

export const kAllActionIds = typedValues(GlobalActions);

export type GlobalActionId = keyof typeof GlobalActions;

export const GlobalActionCategories = {
   Transport: "Transport",
   File: "File",
   Edit: "Edit",
   View: "View",
   Navigation: "Navigation",
   NoteInput: "NoteInput",
} as const;

export const kAllActionCategories = typedValues(GlobalActionCategories);

export type GlobalActionCategory = keyof typeof GlobalActionCategories;
